server:
  port: 8888
spring:
  application:
    name: acctrans-provider-a
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/acctrans
      username: root
      password: 123456

dubbo:
  scan:
    base-packages: com.github.acctrans
  protocol:
    name: dubbo
    port: 20002
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper

mybatis:
  mapper-locations: classpath:mapper/*.xml